name: Deploy

on:
  push:
    branches: main
  workflow_call:

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download website
        uses: actions/download-artifact@v3
        with:
          name: website
          path: .
      - name: Add `.nojekyll` file
        run: touch .nojekyll
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
